services:
  - type: web
    name: chess-app
    env: node
    buildCommand: |
      if [ -f chess-front/package-lock.json ]; then \
        npm ci --prefix chess-front; \
      else \
        npm install --prefix chess-front; \
      fi
      npm run build --prefix chess-front
      if [ -f chess-server/package-lock.json ]; then \
        npm ci --prefix chess-server; \
      else \
        npm install --prefix chess-server; \
      fi
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
